[package]
name = "infra"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["sRow motion Contributors"]

[dependencies]
shared = { workspace = true }
sha2 = "0.10"

[dev-dependencies]
tempfile = { workspace = true }